LIBNAME MDRIVE '\\rmc.local\dfsroot\Dept\Marketing\Analytics\SNAPSHOTS';

DATA APPS(
	keep = LOANNUMBER ApplicationEnterDateonly BRACCTNO 
		   SMALLAMOUNTAPPROVED FINALLOANAMOUNT SELECT_AMOUNT_FINANCED);   
*set dw.appdata;  
set mdrive.tempapps_20190703; *IF CUSTOMERTYPE='NB';
IF LOANNUMBER='' THEN DELETE; 
IF SUBSTR(ApplicationEnterDateonly,1,7)='2019-05' ;

BRACCTNO=LOANNUMBER;

DROP LOANNUMBER ApplicationEnterDateonly   ;
proc sort ; by BRACCTNO;

DATA DW  (KEEP=  BRACCTNO  LOANDATE  TILA_LNAMT  OWNST LNAMT NETLOANAMOUNT  LoanType  SerChg FinChg FeeAmt4  FeeAmt5  FeeAmt6 ) ;
*set MDRIVE.ALLBOOKD_2019YTD; 
SET DW.VW_LOAN;  
IF SUBSTR(LOANDATE,1,7)='2019-05';
proc sort ; by BRACCTNO;

DATA mdrive.TEMP;
MERGE DW (IN=INDW) APPS (IN=INAPPS);  
BY BRACCTNO;  IF INDW AND INAPPS;



DATA snap  (KEEP=  BRACCTNO    tot_insprem ) ;
set MDRIVE.ALLBOOKD_2019YTD; 
*IF SUBSTR(LOANDATE,1,7)='2019-05';
proc sort ; by BRACCTNO;

DATA mdrive.TEMP2;
MERGE mdrive.TEMP (IN=INtemp) snap (IN=INsnap);  
BY BRACCTNO;  IF INtemp AND INsnap;



*PROC SORT NODUPKEY;  *BY BRACCTNO;

/*
DATA LAST;
FORMAT SSN DATE1 DATE2 DATE3 DATE4 DATE5 DATE6 LEAD1 LEAD2 LEAD3 LEAD4 LEAD5 STATUS1 STATUS2 STATUS3 STATUS4 STATUS5 SCORE1 SCORE2 SCORE3 SCORE4 SCORE5 ;
SET DUPES2;

/*
*/
run;
